jobs:
  - job: test
    strategy:
      matrix:
        oldest:
          IMAGE_NAME: ubuntu-16.04
          PYTHON_VERSION: 2.7
          TOXENV: py27-{acme,apache,apache-v2,certbot,dns,nginx}-oldest
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
    - bash: brew install augeas
      condition: startswith(variables['IMAGE_NAME'], 'macOS')
      displayName: Install Augeas
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
        addToPath: true
    - script: python tools/pip_install.py -U tox coverage
      displayName: Install dependencies
    - script: python -m tox
      displayName: Run tox
